### ISSUE TITLE
Create Volunteer Backend Service 

### ISSUE THREAD

**Issue by yalaa90** [Resala-Tech-Community/resalacore#2]
Volunteer User Story:
as Resala employee i would like to create volunteer data from many aspects and integrate with many sub systems like registration , events , questionnaire  ,etc 
volunteer registration:
as Resala employee i should be able to register  volunteer based on scanned qr volunteer id , volunteer data, new volunteer data

Acceptance criteria :

- Create API documentation for mobile team 
- not possible to create duplicated volunteer 
- volunteer name , id , phone , region , can't be empty 

Data model 
```
{
name:text ,
 joinDate:date,
 gender:number,
 notes:text,
 miniCamp:boolean,
 tshirt:boolean,
phoneNumber:text,
extraDetailsJSON:text,
networkTyope:number,
region:number,
birthDate:date,
universityٍٍSpecialization:number,
idNumber:number
volunteerType:number
}
```
for more information please take look at attachment 
[منصة إدارة القوافل _ إدارة المتطوعين _ المعادي.xlsx](https://github.com/Resala-Tech-Community/resalacore/files/4020522/_._.xlsx)

**Comment by FatenElhariry** [comment]
ensuring that we have one one volunteer with this data we can check first with volunteer data then return warning message that for example we have the same phone number related to another volunteer confirm saving any way or cancel based on the user action we will add.
please confirm that is accepted  !

**Comment by aaahussein** [comment]
I would like to ask a question:
Will the Volunteer database contain the people with the role "مسؤول" or it will be a separate database?
@yalaa90 @FatenElhariry

**Comment by yalaa90** [comment]
Dear @FatenElhariry 
i have reviewed please take look and let me know

**Comment by yalaa90** [comment]
> I would like to ask a question:
> Will the Volunteer database contain the people with the role "مسؤول" or it will be a separate database?
> @yalaa90
no it will in different table but in same database
