### ISSUE TITLE
[Spike] shape the final solution for survey     

### ISSUE THREAD

**Issue by yalaa90** [Resala-Tech-Community/resalacore#8]

**Comment by aaahussein** [comment]
How to add myself as the assignee

**Comment by aaahussein** [comment]
I have finished the task and reached a [survey design](https://dbdiagram.io/d/5e214b119e76504e0ef05d8c).  
I also provided documentation for the research at [Nuclino](https://app.nuclino.com/ResalaCore/Core/Survey-Data-ac0e6734-2e60-436c-834d-702ea0c16c8d)
Your comments and reviews are highly appreciated @yalaa90
